//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxaTechAssessment.Providers.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxaTechAssessment.Providers.Domain.Properties.BusinessString", typeof(BusinessString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider ID must be greater than zero..
        /// </summary>
        internal static string InvalidProviderId {
            get {
                return ResourceManager.GetString("InvalidProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider name cannot be null or empty..
        /// </summary>
        internal static string InvalidProviderName {
            get {
                return ResourceManager.GetString("InvalidProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider name must not have a length greater than 30..
        /// </summary>
        internal static string InvalidProviderNameLength {
            get {
                return ResourceManager.GetString("InvalidProviderNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider postal address cannot be null or empty..
        /// </summary>
        internal static string InvalidProviderPostalAddress {
            get {
                return ResourceManager.GetString("InvalidProviderPostalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider postal address must not have a length greater than 200..
        /// </summary>
        internal static string InvalidProviderPostalAddressLength {
            get {
                return ResourceManager.GetString("InvalidProviderPostalAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider type cannot be null or empty..
        /// </summary>
        internal static string InvalidProviderType {
            get {
                return ResourceManager.GetString("InvalidProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider type must not have a length greater than 15..
        /// </summary>
        internal static string InvalidProviderTypeLength {
            get {
                return ResourceManager.GetString("InvalidProviderTypeLength", resourceCulture);
            }
        }
    }
}
